import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true,args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
try{const p=await browser.newPage({viewport:{width:1000,height:800}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/gesture-test',r=>r.fulfill({contentType:'text/html',body:`<style>button{position:relative;z-index:3}#play{position:fixed;left:60px;top:400px;width:100px;height:50px}#detail{position:fixed;left:60px;top:500px;width:100px;height:50px}dialog{width:300px;height:200px}</style><div class="header-right"></div><div id="scene"><canvas style="position:fixed;left:300px;top:100px;width:700px;height:650px"></canvas></div><input id="context-opacity" value="10"><input id="cutaway" type="range" min="0" max="100" value="45"><output id="cut-value">45%</output><button id="play">Play</button><button id="detail">Details</button><dialog id="detail-dialog"><button id="close">Close</button></dialog><script type="module">window.calls={rotate:0,zoom:0,click:0,hover:0,clearSelection:0,input:0,cut:0,play:0,seeks:[],inflight:0,maxInflight:0};window.blank=false;window.app={select:id=>{app.state.selected=id;calls.clearSelection++;},state:{selected:'protein',time:20,rows:[{time:0},{time:100}],playing:true,run:'test'},setTime:async t=>{calls.inflight++;calls.maxInflight=Math.max(calls.maxInflight,calls.inflight);await new Promise(r=>setTimeout(r,120));app.state.time=t;calls.seeks.push(t);calls.inflight--;},view:{gestures:{rotate:()=>calls.rotate++,zoom:()=>calls.zoom++,click:()=>calls.click++,hover:()=>{calls.hover++;return !window.blank;},clear:()=>{}}}};document.querySelector('#cutaway').oninput=e=>{calls.cut++;document.querySelector('#cut-value').value=e.target.value+'%';};document.querySelector('#play').onclick=()=>{app.state.playing=!app.state.playing;calls.play++;};document.querySelector('#detail').onclick=()=>document.querySelector('dialog').showModal();document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();window.Worker=class{constructor(){window.fakeWorker=this;}postMessage(d){if(d.type==='init')setTimeout(()=>this.onmessage({data:{type:'ready'}}),0);else d.bitmap.close();}terminate(){}};import {initHandControl} from '/hand-control.js';document.querySelector('#context-opacity').oninput=()=>calls.input++;initHandControl(()=>app);</script>`}));await p.goto((process.env.APP_URL||'http://127.0.0.1:8766')+'/gesture-test');await p.locator('#hand-toggle').click();await p.locator('#hand-start').click();await p.waitForFunction(()=>window.fakeWorker);await p.locator('#hand-toggle').click();
async function emit(kind='point',pos=null,angle=0){await p.evaluate(({kind,pos,angle})=>{const a=Array.from({length:21},()=>({x:.5,y:.7}));a[0]={x:.5,y:.9};for(let f=0;f<4;f++){const b=5+f*4;for(let j=0;j<4;j++)a[b+j]={x:.38+f*.08,y:.65-j*.13};if(kind!=='open'&&f>0)a[b+3].y=.8;}a[4]={x:.2,y:.5};if(kind==='pinch')a[4]={...a[8],x:a[8].x+.015};if(kind==='fist')for(const tip of [8,12,16,20])a[tip]={x:.5,y:.8};if(pos){const dx=(1-pos.x)-a[8].x,dy=pos.y-a[8].y;for(const p of a){p.x+=dx;p.y+=dy;}}const c={...a[9]};const landmarks=a.map(p=>({x:c.x+(p.x-c.x)*Math.cos(angle)-(p.y-c.y)*Math.sin(angle),y:c.y+(p.x-c.x)*Math.sin(angle)+(p.y-c.y)*Math.cos(angle)}));fakeWorker.onmessage({data:{type:'result',landmarks:kind==='none'?[]:[landmarks],handedness:[[{categoryName:window.testLeft?'Right':'Left',score:.99}]],ms:10}});},{kind,pos,angle});await p.waitForTimeout(85);}
async function dwellAt(selector){const b=await p.locator(selector).boundingBox();const pos={x:(b.x+b.width/2)/1000,y:(b.y+b.height/2)/800};await emit('none');for(let i=0;i<16;i++)await emit('point',pos);}
await p.evaluate(()=>window.testLeft=true);for(let i=0;i<16;i++)await emit('point');assert(await p.locator('#hand-cursor').isHidden());assert.equal(await p.evaluate(()=>calls.click),0);await p.evaluate(()=>window.testLeft=false);await dwellAt('#play');assert.equal(await p.evaluate(()=>calls.play),1);assert.equal(await p.evaluate(()=>app.state.playing),false);
await dwellAt('#detail');assert(await p.locator('dialog').evaluate(d=>d.open));await dwellAt('#close');assert.equal(await p.locator('dialog').evaluate(d=>d.open),false);
await emit('none');for(let i=0;i<16;i++)await emit('point');assert.equal(await p.evaluate(()=>calls.click),1);for(let i=0;i<5;i++)await emit('point');assert.equal(await p.evaluate(()=>calls.click),1);
await emit('pinch');await emit('point');assert.equal(await p.evaluate(()=>calls.click),1);
await emit('none');await p.evaluate(()=>window.blank=true);for(let i=0;i<16;i++)await emit('point');assert.equal(await p.evaluate(()=>calls.clearSelection),1);assert.equal(await p.evaluate(()=>app.state.selected),null);for(let i=0;i<5;i++)await emit('point');assert.equal(await p.evaluate(()=>calls.clearSelection),1);await p.evaluate(()=>{window.blank=false;app.state.selected='protein';});
await emit('none');
async function cutHands(spread){await p.evaluate(spread=>{function L(x){const a=Array.from({length:21},()=>({x:.5+x,y:.7}));a[0]={x:.5+x,y:.9};for(let f=0;f<4;f++){const b=5+f*4;for(let j=0;j<4;j++)a[b+j]={x:.38+f*.08+x,y:.65-j*.13};if(f>0)a[b+3].y=.8;}a[2]={x:.4+x,y:.64};a[3]={x:.3+x,y:.64};a[4]={x:.2+x,y:.64};return a;}fakeWorker.onmessage({data:{type:'result',landmarks:[L(-spread),L(spread)],ms:10}});},spread);await p.waitForTimeout(85);}
await cutHands(.15);assert.equal(await p.locator('#cutaway').inputValue(),'45');for(let i=0;i<8;i++)await cutHands(.20);assert(Number(await p.locator('#cutaway').inputValue())>45);await cutHands(.15);for(let i=0;i<8;i++)await cutHands(.1);assert(Number(await p.locator('#cutaway').inputValue())<45);const retained=await p.locator('#cutaway').inputValue();await emit('none');await cutHands(.25);assert.equal(await p.locator('#cutaway').inputValue(),retained);assert.equal(await p.evaluate(()=>calls.zoom),0);assert((await p.locator('#cut-value').textContent()).endsWith('%'));
await emit('none');await p.evaluate(()=>app.state.playing=true);for(let i=0;i<9;i++)await emit('open');assert.equal(await p.locator('.hand-countdown').textContent(),'3');assert(await p.locator('.aura-stage').isHidden());assert(await p.locator('.aura-preview').isHidden());await p.evaluate(()=>window.testLeft=true);for(let i=0;i<12;i++)await emit('open');assert.equal(await p.locator('.hand-countdown').textContent(),'2');for(let i=0;i<12;i++)await emit('open');assert.equal(await p.locator('.hand-countdown').textContent(),'1');for(let i=0;i<14;i++)await emit('open');assert(await p.locator('.hand-countdown').evaluate(e=>e.hidden));assert(await p.evaluate(()=>handControl.debug().timeMode));await p.screenshot({path:'logs/time-stone-effect.png'});await emit('open',null,Math.PI/2);await p.waitForFunction(()=>app.state.time===0);await emit('open',null,-Math.PI/2);await p.waitForFunction(()=>app.state.time===100);await emit('fist');await p.evaluate(()=>window.testLeft=false);assert.equal(await p.evaluate(()=>handControl.debug().timeMode),false);assert(await p.locator('.aura-stage').isHidden());assert.equal(await p.evaluate(()=>calls.maxInflight),1);await p.waitForFunction(()=>app.state.playing);await p.evaluate(()=>{app.state.playing=false;});await emit('none');for(let i=0;i<45;i++)await emit('open');assert(await p.evaluate(()=>handControl.debug().timeMode));await emit('fist');await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>app.state.playing),false);
await p.evaluate(()=>{for(const id of ['membrane','dna','rna','ribosome','rnap','protein']){const b=document.createElement('button');b.dataset.component=id;b.hidden=true;document.body.append(b);}});
async function leftDigit(n){await p.evaluate(n=>{const l=Array.from({length:21},()=>({x:.5,y:.65}));l[0]={x:.5,y:.9};for(let f=0;f<4;f++){for(let j=0;j<4;j++)l[5+f*4+j]={x:.38+f*.08,y:.65-j*.13};if(!(n===6?f===3:f<Math.min(n,4)))l[8+f*4].y=.8;}l[2]={x:.4,y:.65};l[4]=n>=5?{x:.2,y:.5}:{...l[5]};fakeWorker.onmessage({data:{type:'result',landmarks:[l],handedness:[[{categoryName:'Right',score:.99}]],ms:10}});},n);await p.waitForTimeout(85);}
for(const [n,id] of [[1,'membrane'],[2,'dna'],[3,'rna'],[4,'ribosome'],[5,'rnap'],[6,'protein']]){await emit('none');for(let i=0;i<14;i++)await leftDigit(n);assert.equal(await p.evaluate(()=>app.state.selected),id);assert(await p.locator('#hand-cursor').isHidden());}
for(let i=0;i<45;i++)await leftDigit(5);assert.equal(await p.evaluate(()=>handControl.debug().timeMode),false);
await p.evaluate(()=>{app.state.playing=true;});await emit('none');for(let i=0;i<45;i++)await emit('open');assert(await p.evaluate(()=>handControl.debug().timeMode));await emit('none');await p.waitForFunction(()=>app.state.playing);
await p.evaluate(()=>handControl.stop());assert.deepEqual(errors,[]);console.log('PASS UI dwell, left digits, countdown survives changing handedness, rotation/endpoints/fist exit, playback restoration and two-hand cut');}finally{await browser.close();}
