import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {sample} from './chest-tap.mjs';
const browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
try{const p=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];p.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});await p.route('**/gesture-test',r=>r.fulfill({contentType:'text/html',body:`<script type="importmap">{"imports":{"three":"/vendor/three.module.js"}}</script><div class="header-right"></div><script type="module">window.Worker=class{constructor(){window.fakeWorker=this;}postMessage(d){if(d.type==='init')setTimeout(()=>this.onmessage({data:{type:'ready',poseEnabled:true}}),0);else d.bitmap.close();}terminate(){window.terminated=true;}};import {initHandControl} from '/hand-control.js';initHandControl(()=>({state:{},view:{gestures:{clear(){}}}}));</script>`}));await p.goto((process.env.APP_URL||'http://127.0.0.1:8766')+'/gesture-test');
async function trigger(){if(await p.locator('#hand-panel').isHidden())await p.locator('#hand-toggle').click();await p.locator('#hand-start').click();await p.waitForFunction(()=>window.fakeWorker&&document.querySelector('video').videoWidth>0);for(const inside of [false,true,true,false,true,true]){await p.evaluate(result=>fakeWorker.onmessage({data:{type:'result',...result,ms:15}}),sample({inside}));await p.waitForTimeout(100);}await p.waitForSelector('#iron-suit');}
await trigger();assert.equal(await p.locator('#chest-feedback').count(),0);assert(!((await p.locator('#hand-instructions').textContent()).includes('装甲')));const bounds=await p.locator('#iron-suit').boundingBox(),wrap=await p.locator('.hand-video-wrap').boundingBox();assert(bounds.width<=wrap.width+1&&bounds.height<=wrap.height+1&&bounds.width<400);let d=await p.evaluate(()=>handControl.debug());assert(d.suiting&&d.active);assert.deepEqual(d.tracks,[]);assert(await p.evaluate(()=>terminated));const frozen=await p.locator('.iron-freeze').evaluate(c=>c.toDataURL());await p.waitForFunction(()=>document.querySelector('#iron-suit')?.dataset.phase==='assembled');const model=await p.evaluate(()=>handControl.debug().suit);assert(model.modelLoaded&&model.meshes>50&&model.clips>0&&model.drawCalls>50);assert.equal(await p.locator('.iron-freeze').evaluate(c=>c.toDataURL()),frozen);await p.screenshot({path:'logs/iron-suit-assembled.png'});await p.waitForFunction(()=>document.querySelector('#iron-suit')?.dataset.phase==='salute');await p.waitForTimeout(800);await p.screenshot({path:'logs/iron-suit-salute.png'});await p.waitForFunction(()=>document.querySelector('#iron-suit')?.dataset.phase==='crt');await p.waitForSelector('#iron-suit',{state:'detached'});d=await p.evaluate(()=>handControl.debug());assert(!d.active&&!d.suiting);assert.deepEqual(d.tracks,[]);assert(await p.locator('#hand-panel').isHidden());
await trigger();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>handControl.debug().active),false);assert.equal(await p.locator('#iron-suit').count(),0);
if(await p.locator('#hand-panel').isHidden())await p.locator('#hand-toggle').click();await p.locator('#hand-start').click();await p.waitForFunction(()=>document.querySelector('video').videoWidth>0);await p.keyboard.press('Escape');await p.waitForSelector('#iron-suit');assert((await p.evaluate(()=>handControl.debug())).suiting);assert.deepEqual(await p.evaluate(()=>handControl.debug().tracks),[]);await p.keyboard.press('Escape');assert.equal(await p.locator('#iron-suit').count(),0);
await trigger();await p.evaluate(()=>handControl.stop());assert.equal(await p.locator('#iron-suit').count(),0);assert.deepEqual(await p.evaluate(()=>handControl.debug().tracks),[]);assert.deepEqual(errors,[]);console.log('PASS double-tap trigger, immutable frozen frame, assembly/salute/CRT sequence, camera released, automatic mode exit, Escape and manual cancellation');}finally{await browser.close();}
