import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createGestureScene} from '../../gesture-scene.js';
import {initHandControl} from '../../hand-control.js';
import {CellSoundEngine} from '../../cell-sound.js';
const $=s=>document.querySelector(s),container=$('#scene'),scene=new THREE.Scene(),cell=new THREE.Group();scene.add(cell);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.localClippingEnabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;container.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(4,3,12);const controls=new OrbitControls(camera,renderer.domElement);controls.minDistance=2;controls.maxDistance=30;const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight(0xfff5da,0x685770,2));
const clipping=new THREE.Plane(new THREE.Vector3(0,0,-1),5),groups={},temp=new THREE.Object3D();
for(const [index,[id,color]]of Object.entries({amber:'#c6a158',violet:'#887299',teal:'#65958b'}).entries()){
 const geometry=new THREE.IcosahedronGeometry(.095+index*.035,1),material=new THREE.MeshStandardMaterial({color,roughness:.3,metalness:.15,clippingPlanes:[clipping]}),mesh=new THREE.InstancedMesh(geometry,material,300);mesh.userData.component=id;cell.add(mesh);groups[id]=mesh;
}
const state={ready:true,run:'synthetic',selected:null,time:0,playing:true,speed:1,rows:Array.from({length:61},(_,time)=>({time}))};let audio=null,audioContext=null;
function select(id){state.selected=id;for(const [key,mesh]of Object.entries(groups)){mesh.material.opacity=id&&key!==id?Number($('#context-opacity').value)/100:1;mesh.material.transparent=mesh.material.opacity<1;mesh.material.depthWrite=!mesh.material.transparent;mesh.visible=mesh.material.opacity>0;}}
function setTime(t){state.time=THREE.MathUtils.clamp(Number(t),0,60);$('#time-slider').value=state.time;$('#clock').textContent=state.time.toFixed(1)+' s';}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function pick(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(Object.values(groups).filter(m=>m.visible)).find(h=>clipping.distanceToPoint(h.point)>=0);}
const bridge=createGestureScene({scene,camera,cell,controls,canvas:renderer.domElement,pick,selectHit:h=>select(h.object.userData.component),invalidate(){},cancelMotion(){}});
const app={state,select,setTime,view:{gestures:bridge}};initHandControl(()=>app);window.particleLab=app;
let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5)select(pick(e)?.object.userData.component||null);});
for(const b of document.querySelectorAll('[data-group]'))b.onclick=()=>select(b.dataset.group);$('#clear').onclick=()=>select(null);$('#context-opacity').oninput=()=>select(state.selected);$('#cutaway').oninput=e=>clipping.constant=(Number(e.target.value)/100-.5)*10;$('#time-slider').oninput=e=>setTime(e.target.value);$('#play').onclick=()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'Pause':'Play';};
$('#sound').onclick=async()=>{if(audio){audio.dispose();audio=null;await audioContext.close();$('#sound').textContent='Enable sound';return;}audioContext=new AudioContext();await audioContext.resume();audio=new CellSoundEngine(audioContext,{profiles:{amber:{hz:190,q:.6,grain:.3,rate:12,ref:300},violet:{hz:450,q:.6,grain:.08,rate:30,ref:300},teal:{hz:950,q:.55,grain:.12,rate:20,ref:300}}});$('#sound').textContent='Mute sound';};
let last=performance.now();function tick(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(state.playing)setTime((state.time+dt)%60);let k=0;for(const mesh of Object.values(groups)){for(let i=0;i<300;i++){const phi=i*2.39996,t=state.time*.12+k;temp.position.set(Math.cos(phi+t)*(.8+i%19*.08)+(k-1)*2.3,Math.sin(i*.73+t)*1.6,Math.sin(phi*.8+t)*1.5);temp.rotation.set(phi,t,phi*.3);temp.updateMatrix();mesh.setMatrixAt(i,temp.matrix);}mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();k++;}audio?.update({ready:true,selected:state.selected,counts:{amber:300,violet:300,teal:300},activity:{}},{audible:state.playing&&!document.hidden,volume:.25});controls.update();renderer.render(scene,camera);requestAnimationFrame(tick);}requestAnimationFrame(tick);
function resize(){renderer.setSize(container.clientWidth,container.clientHeight);camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(container);resize();document.addEventListener('visibilitychange',()=>{if(document.hidden)audioContext?.suspend();else audioContext?.resume();});window.addEventListener('pagehide',()=>{audio?.dispose();audioContext?.close();});
